
openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "Contexto game!"
  version: "1.0.0"
#comments are like this. We're probably going to need a lot of these.
servers:
  - url: "/api"

components:
  parameters:
    guess:
      name: guess #Needs a name and where its in. Schema i guess tells it what in fo it needs to have
      in: path #Path is in url, query goes after a ?
      schema:
        type: "string" 
      required: true
      description: "guess"

paths: 
  /generator/{guess}:
    post:
      operationId: "generator.guess"  
      tags:
        - "Guess" 
      summary: "Guesses a word"  
      parameters:  
        - $ref: "#/components/parameters/guess"
      responses: 
        "200":
          description: "Guess successful"
  /generator:
    get:
      operationId: "generator.generate_orderings"
      summary: "Sets the word for a user"
      responses:
        "200":
          description: "Guess generated"  