
openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "Contexto game!"
  version: "1.0.0"
#comments are like this. We're probably going to need a lot of these.
servers:
  - url: "/api"

components:
  parameters:
    guess:
      name: guess #Needs a name and where its in. Schema i guess tells it what in fo it needs to have
      in: path #Path is in url, query goes after a ?
      schema:
        type: "string" 
      required: true
      description: "guess"

paths: 
  /guess: 
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                guess:
                  type: string
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: object
              
  /generate:
    get:
      operationId: "generate_orderings" 
      summary: "Sets the word for a user"
      responses:
        "200":
          description: "word ordering generated" 

  # /get_previous_guesses:
  #   get:
  #   operationId: "get_previous_guesses"
  #   summary: "Gets the history of the guesses"
  #   responses:
  #     "200 ": 
  #       description: "U got the guess history yay"